version: '3'
services:
  logstash1:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE} -Xmx${ES_HEAP_SIZE}"
  kibana1:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch1:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
