version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=elasticsearch1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=elasticsearch1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  kibana1:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch1:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
